### ISSUE TITLE
last.fm error responses causing error

### ISSUE THREAD

**Issue by chrismou** [dandelionmood/php-lastfm#11]
Since the last.fm redesign, a number of the endpoints seem to have dropped offline (apparently, to be brought back at some point, but not 100% confirmed yet).

https://getsatisfaction.com/lastfm/topics/event-getinfo-and-geo-getevents-returning-error-no-method-name

As a result, while calling event.getInfo I'm getting the following response:

`{"error":3,"message":"Invalid Method - No method with that name in this package"}`

This would be fine, except [this line](https://github.com/dandelionmood/php-lastfm/blob/master/lib/Dandelionmood/LastFm/LastFm.php#L162) assumes "lines" always exists, where it doesn't - at least, it doesn't anymore (!)

So as a result, I'm seeing an `Undefined property: stdClass::$links` error

I don't know if it's removal was temporary - to be honest, I've only just started using the last.fm API so I'm unsure how the errors were structured previously.  I'm happy to put in a pull request with a quick fix if you're busy, or can leave it to you if you want to deal with it?

Let me know!

**Comment by dandelionmood** [comment]
Hi @chrismou,

Well, it's entirely possible that `$links` are/were not always present in the error and that my code was a little lazy in that regard ;) … If you could submit a pull request testing the presence of `$links` before doing the `implode()`, for instance, that'd be great :) !

Thanks for your help :) !
