### ISSUE TITLE
Object of class stdClass could not be converted to string

### ISSUE THREAD

**Issue by simonfranz** [dandelionmood/php-lastfm#7]
Hi there,
I get an error if i caalling this below.
It's in this file dandelionmood/lastfm/lib/Dandelionmood/LastFm/LastFm.php line 161

        $lastfm = new \Dandelionmood\LastFm\LastFm(env("LASTFM_APIKEY"), env("LASTFM_APISECRET"));
        $tracks = $lastfm->track_getSimilar(
            array(
                'artist' => 'Robbie Williams,
                'track' => 'Feel',
                'limit' => 50,
                'autocorrect' => '1',
            )
        );

Maybe this can be fixed here?

**Comment by dandelionmood** [comment]
Hi @simonfranz,
can you give me more detail about the error you see ?
What is the content of `$json` when you have a problem ?

Pierre

**Comment by simonfranz** [comment]
thanks for the quick response.

    "{"error":3,"message":"Invalid Method - No method with that name in this package"}"

it seems that lastfm has removed this method from their api, despite that it's still listed on the api-docs.
I cannot get any content from this link http://www.last.fm/api/show/track.getSimilar

Sorry for the inconvinience

**Comment by simonfranz** [comment]
seems that there are quite some api's down.
https://getsatisfaction.com/lastfm/topics/api-known-issues?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Breply_id%5D=16033774#reply_16033774

So this isn't any package-issue :+1: 
Waiting for lastfm to fix this

**Comment by dandelionmood** [comment]
Thanks for the heads up @simonfranz, good luck with your project :) !

**Comment by simonfranz** [comment]
thanks you too, for this awesome package. It's really helping shortening the development-time :)
